### ISSUE TITLE
Need recovery mehanism for a wrong apple id / password

### ISSUE THREAD

**Issue by jamwal** [pixelomer/AltDeploy#17]
Accidentally saved a wrong apple id password. Installation failed with "Incorrect Apple ID or password".
Removed the device, reconnected and retried. It proceeded without asking for user details and failed again. 
Deleted the application, re-downloaded and retried. Still the same error. 

After few failures apple id is locked.
I feel user credentials should be asked on each install.

**Comment by pilflo** [comment]
I managed to change my Apple ID credentials AltDeploy(top menu bar) > AppleID

**Comment by Nawaf-NM** [comment]
> 
> 
> Accidentally saved a wrong apple id password. Installation failed with "Incorrect Apple ID or password".
> Removed the device, reconnected and retried. It proceeded without asking for user details and failed again.
> Deleted the application, re-downloaded and retried. Still the same error.
> 
> After few failures apple id is locked.
> I feel user credentials should be asked on each install.

same here dude :(

**Comment by jamwal** [comment]
Thanks ! A noob mistake.
