### ISSUE TITLE
The app is invalid error?

### ISSUE THREAD

**Issue by telepati** [pixelomer/AltDeploy#18]
When I try to add IPA to iPhone I am getting the app is invalid error. How can we fix that?

<img width="532" alt="Screen Shot 2020-01-08 at 16 03 07" src="https://user-images.githubusercontent.com/3812286/71980196-8c300e00-3230-11ea-83cd-2bafd91ea847.png">

**Comment by taronaeo** [comment]
Your IPA might be corrupted or not built properly. Have you tried installing other IPAs yet?

**Comment by telepati** [comment]
> Your IPA might be corrupted or not built properly. Have you tried installing other IPAs yet?

Yes, some IPA's work some don't.
