### ISSUE TITLE
Linux support status

### ISSUE THREAD

**Issue by akasandra** [pixelomer/AltDeploy#40]
What is the reason it is not compatible with Linux? With active phase of development, do you plan to support Linux?

**Comment by pixelomer** [comment]
Support for Windows/Linux isn't planned right now. The code is written in Swift and Objective-C and it relies on some things that only exist on macOS.

**Comment by akasandra** [comment]
Just to note that Swift is Linux-compatible. Apple frameworks aren't, so OK 👍
