### ISSUE TITLE
An error occurred while installing the app.

### ISSUE THREAD

**Issue by MatthewCerza** [pixelomer/AltDeploy#43]
Tried on a MacBook Pro 2018 running 10.14.6 (18G103) using a Type C to Lightning Cable, and a Type A to Lighning Cable. Also tried on a Mac Pro 2012 running 10.14.6 (18G2022) using a Type A to Lightning cable. 

Using an iPhone XS 256GB on 12.4

Any ideas?
![Screen Shot 2020-01-12 at 12 03 36 PM](https://user-images.githubusercontent.com/47721459/72224871-e8967480-3533-11ea-9d0e-6ea342320cde.png)

**Comment by SanderDelden** [comment]
Please refer to #21

**Comment by MatthewCerza** [comment]
Forgot I already had an old version of unc0ver on my device, removing it fixed the issue. Thanks!
