### ISSUE TITLE
Incompatible with lower version OSX 

### ISSUE THREAD

**Issue by lich4** [pixelomer/AltDeploy#48]
Incompatible with lower version OSX  
mine is 10.11.6

**Comment by wwwonka** [comment]
Argh same here, I am using Sierra 10.12.6 and will not update my OS any time soon. How hard does making the app work with lower macOS versions is? Is there any chances we might see altDeploy be compatible with those any time soon?

**Comment by northwinds** [comment]
Yeah - I'm on 10.13.6 and that doesn't work either!

**Comment by asylumexp** [comment]
https://github.com/pixelomer/AltDeploy/issues/12

**Comment by geordi1** [comment]
How about back to 10.10.5 please?
