### ISSUE TITLE
"Incorrect Apple ID or Password."

### ISSUE THREAD

**Issue by anon00000** [pixelomer/AltDeploy#49]
I tried to use the Apple ID password, then generating an app-specific password. I don't know what's causing the error.

**Comment by Photonious** [comment]
I had the same issue. I created a new apple ID and did not enable Two Factor Auth. I don't think AltDeploy supports the app-specific password option.

**Comment by anon00000** [comment]
> I had the same issue. I created a new apple ID and did not enable Two Factor Auth. I don't think AltDeploy supports the app-specific password option.

Tried doing what you did, now returns "Your Apple ID or password was entered incorrectly. (-20101)"

**Comment by anon00000** [comment]
Nvm, forgot to sign in with the new Apple ID on my phone. Thx for the help!
