### ISSUE TITLE
Crashes when installing IPA

### ISSUE THREAD

**Issue by asylumexp** [pixelomer/AltDeploy#5]
My version of macOS is Catalina 10.15.2, the device being installed to was a iPad 7 (2019/Educational), the Mac was a MacBook Air (Early 2015).

log: [log.txt](https://github.com/pixelomer/AltDeploy/files/4027916/log.txt)

Happened at 9:40pm GMT on the 6/1/20

**Comment by asylumexp** [comment]
the iPA was signed by a different AppleID using iOS App Signer though that shouldn't affect it? just thought I should mention it.

**Comment by asylumexp** [comment]
I’m also using and have enabled the Altstore Mail Plugin, the one direct from AltServer.

**Comment by taronaeo** [comment]
Have you tried installing other IPAs as well just to verify if your IPA is corrupted or if the application is actually having a problem?

If you need to try, here is one that I have personally tested and worked 100% on my system https://github.com/PopcornTimeTV/PopcornTimeTV/releases

If it does work, then it will just be that your IPA is corrupted.

**Comment by asylumexp** [comment]
ok, I’ll try that now

**Comment by asylumexp** [comment]
Thanks for telling me that. I should’ve actually had tested it with other iPAs before coming in here
