### ISSUE TITLE
"Manage Plug-Ins" button missing in High Sierra (have tried terminal commands)

### ISSUE THREAD

**Issue by BartmanEH** [pixelomer/AltDeploy#52]
I've tried `sudo /Applications/AltDeploy.app/Contents/MacOS/AltDeploy -I` and `defaults write com.apple.mail EnableBundles -bool true` and restarted Mail and restarted High Sierra but I cannot get the "Manage Plug-ins" button to show so I cannot enable the plug-in although I see it in: `/Library/Mail/Bundles` where I see a folder called `AltPlugin.mailbundle`

**Comment by BartmanEH** [comment]
I just bothered to try AltDeploy to see what error I would get not having enabled the mail plug-in and to my surprise, it worked! I can't explain why I don't have an "Manage Plug-Ins" button in Mail 11.5 and, despite what the tutorial video shows that enabling the plug-in is required, it doesn't seem to be required for me.

**Comment by pixelomer** [comment]
IIRC all plugins are enabled on High Sierra by default.
