### ISSUE TITLE
Cannot connect to device error when sending provisioning profile

### ISSUE THREAD

**Issue by GalaxyNinja66** [pixelomer/AltDeploy#9]
It'll work just fine, but when it get's to "sending provisioning profile" it gives a "cannot connect to device" error and stops.

**Comment by addy399** [comment]
same here.

**Comment by golgotron** [comment]
Trust your device first. it works for me.

**Comment by addy399** [comment]
> Trust your device first. it works for me.

Thank you for your help, it working now !

**Comment by pixelomer** [comment]
#7 is a similar issue and looks like it's related to the device not being trusted. Does the solution there solve your problem?

**Comment by pixelomer** [comment]
> > Trust your device first. it works for me.
> 
> Thank you for your help, it working now !

Oh, looks like it does ¯\\\_\(ツ\)\_/¯
